apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-webhook
  namespace: flux-system
spec:
  type: github
  events:
    - push
  resources:
    - kind: Kustomization
      name: apps
  secretRef:
    name: webhook-token
