# This is the unencrypted version.
# It will be encrypted to grafana-admin-secret.enc.yaml using SOPS.
apiVersion: v1
kind: Secret
metadata:
    # The name of the Kubernetes Secret that will be created
    name: grafana-admin-credentials
    namespace: monitoring
stringData:
    #ENC[AES256_GCM,data:jP0l8MEWEtZExtqPntrAKF6JOeePcTWUZ03sVZww6hzMAD65N376KSh0mVSZr+LCbLGbMibBqrALeKcXvt0GPGJVkGFOKSU=,iv:muAOYO58jdFyPA0PyrQDIYkfTxO3jdgHCGgAyZdN/ZQ=,tag:yplcBKyY0wUmJb4YKgKGSA==,type:comment]
    adminPassword: ENC[AES256_GCM,data:A+ThqzEdQ0y3kZ1iI86i,iv:kXOO2ISu5tSri0BRheRMt7Pd8Bp4tc9UzkjLBQUuPb0=,tag:mOVsgbrFjIHdTC0zNizH5w==,type:str]
sops:
    age:
        - recipient: age1c5ms02a0q5kay0gy0p5w9qfrjmww34ztdmq6hf4r7kec4w02ueyqm54mu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVkhNNUFaUkhmcmtjWGpI
            OWlMQ0dyODI1RHR3Ylg3K3RkVS9FSytnUHhjCmJ4SXVhUXBlTXd3bTNVYUhGRkdW
            YlFmTmlmLzRhc3A5RWtoR0pqVkF0RGcKLS0tIGVDc2FUc0ZtUGowUkt1cjlVQkFG
            SHFYcWllRy9ESXZTMGJ6WjB5UUVlc3MKtQa+RA8ke33qT6DRCHlEzb0+ceWnkijE
            DrvwNymXCDQ+EFcpJgfgk+hpDforjNKeVt0LTzeyY/FcPPnZdI9wRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T23:28:45Z"
    mac: ENC[AES256_GCM,data:o+byMoMqtTugClo5XkRE1w7C2/6qnxIebeDTHtb86cMTyLsqt38UuhVwSwH0wKe76Y99juCJSl5L2E67nQUvQF/Yaq6f8+4h2JLlF2uGInzn1nl0rEKgFcchBF8BeCQNr5rNmrzlxPimjy+js93/BPcaV4YhPDvw0EamOs5fTDI=,iv:PPjl8+7Z6x1cEoK8wpb5RKyBeEBJYdO3qFkt5NhJ2lM=,tag:BrrqdLdHaOEk9lVX3HT/UA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
