# This is the unencrypted version.
# It will be encrypted to grafana-admin-secret.enc.yaml using SOPS.
apiVersion: v1
kind: Secret
metadata:
    # The name of the Kubernetes Secret that will be created
    name: grafana-admin-credentials
    namespace: monitoring
stringData:
    #ENC[AES256_GCM,data:rZPRR2999KR8Ak4Hrj0m5GV/UtqZMUfahuTM2AljuriWs4/euK53p94goBYMf5eJPJR2kzdUecJydnWf1RR1mkWforRg2jw=,iv:OX9/dWmK0y7MEMDfRPoHYayaU1hovl06UMS5/k085As=,tag:SnY4724kjyZad0ixJb4s4w==,type:comment]
    adminPassword: ENC[AES256_GCM,data:esZ/6fRbMJTNPb9kUIJF,iv:IeR8hF1NjZP3+zkEE3M3jPSUuDrO8lpHOSET09jsQb0=,tag:Fuj9pM71IseRuYPvuySakw==,type:str]
sops:
    age:
        - recipient: age1c5ms02a0q5kay0gy0p5w9qfrjmww34ztdmq6hf4r7kec4w02ueyqm54mu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRGQ5SHhBTEJzV0diTjBq
            cW1xZGFWeG1OMmlWNUlPbytYTW1DRk9MYlJRCkNhY1FqWXZjYm44Mjg2U3VuVjlw
            anZ3enk3VDNhbTVsTWxObUlwRUs1OTgKLS0tIG1FR1VNc0t1MFltN0YzNGVFNWw2
            QXU3aEVpaUYyU2YweElaZXJqUmtDTjgKysSjoWDErNBk6R2ukDEcZmxWQrCYsttj
            FVU7P7AZr0NvnrVhFESDlJq+i6ucvGPoIXiQpQPPPDoST5QPuqQKdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-16T23:59:37Z"
    mac: ENC[AES256_GCM,data:Lnoc26FVmVKahYygCXH7Wmh1kdilgMyuU+8Dqdnvkzua2qeTiupcDbfYTzpG7xnmOtIJ80rNxtvje+TvGnv0FNrCHQj+DZFE2QKRBgEbtRV3uuFMpWuhDMoRSzX/HlZpoWNoQ5gap0J0X8Mt0x6Hcnpv7qVJ76eoMF5XB/Irtk8=,iv:zJ+OQD05247s6NaD3FU1AjO829HGvPJe7pZhxMyJ+Zs=,tag:5wtQv+sgQhOCEfFptJjz3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
