apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wallabag
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - persistent-volume.yaml
  - wallabag-secret.enc.yaml
