# clusters/staging/cloudflared/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure/base/cloudflared
  - cloudflare-secret.enc.yaml
