apiVersion: ENC[AES256_GCM,data:TAk=,iv:raGfNkJUfZob65//qHdCcDZFUi9HKFOWhDDv4TmhT/g=,tag:8AF3KpsFrfYJA1ux1MdQ3g==,type:str]
kind: ENC[AES256_GCM,data:RrGnPpVf,iv:d5VVgKxnhr9xC0pU/ngfyux2F6pv3w5uzEnZiRfkO7c=,tag:RPA2qG93sfszmzed0GF0GQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3O51lGGVykwB/B0S5JSrzU8EJ2k=,iv:IbD5A5rsWdETFpfuAXwF3OBVlywS8aK+T4okJc5OkMw=,tag:Nas7f2sJ9gSKJFlNgR289Q==,type:str]
    namespace: ENC[AES256_GCM,data:8kNGwgEOGsY=,iv:ez+BFetX5YDYH5jNnhNKNPYRlsftVrNP2h3GF76ZAyo=,tag:K+qcUHSF0ZR5oLG6hg+VKA==,type:str]
type: ENC[AES256_GCM,data:GUEs2O1E,iv:tz83iOWdSUIKrpWS0JICJy76HTyA4lsn4+8VH1KOgJg=,tag:kWH+gylzds2lbJhLHldjEw==,type:str]
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:pG43JWGIF60=,iv:8EChq5Xghf/m3UNXst27BtcIcMaWmdIxAKb9Mm/iSbE=,tag:pw21dN28p5bsPWZVxKyJ+g==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:VR+yrivHKeeWWHGoYn2DtUOo8CdqQbvVBvSOFA==,iv:O57fOUwxEchjFD2xEzyQPcemLfPs8V3Uv/Y683/+FkA=,tag:RnmBI+qMzTRLM6RTrMfA9g==,type:str]
sops:
    age:
        - recipient: age1c5ms02a0q5kay0gy0p5w9qfrjmww34ztdmq6hf4r7kec4w02ueyqm54mu3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZNHVhUEl1L044bzY0ZFN4
            T3B3L3RZWkZhVitVVGZiZmpsVmFqcWo0L2pVCkZlRlB6MXlZTkpHMGhwYUxTTHNm
            azRycDhlOFYySENVTmJNY09iWGxkTUEKLS0tIFQ1MkE3Wll3b2J6WW5ZSnJxMXR0
            djhHcHlZVWJiNVJmU1RoSzZWRUNXZXcKJtddCF67k+083K2tcRZ9kmBvk66WaiA2
            EqYCAehzIGpMETD4yqFgoBVBwHIKOuRxSNnjSHVCpq1PcsdiFIN27w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-11T11:08:21Z"
    mac: ENC[AES256_GCM,data:gYbDNBF8ROp/KLv6OeKUEW8MUAyZwEfnfZwZh9T0DfJf4bclGCYvhlEWnGAZZ+USHP/Ty6m9R131/sFWEk9dOSDYr9Y3Qk2IQpLDI1v3Y9rN/bAJa4s7KRja/wbzk2y6E9nEd8R4fsJCgjafAa7fpdG3crU5xviffk6G1d/5MrU=,iv:FXsEzm/Ezhjvnk88LyVZMiD4G6EFHszm9HdJ3vkw4aw=,tag:IlUmUpDcRFxSF1qe+RrQiQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.1
